In [2]:
#classifications
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [8]:
#1
data = pd.read_csv("/content/booking.csv")
df = pd.DataFrame(data)


df.head()

,Booking_ID,number of adults,number of children,number of weekend nights,number of week nights,type of meal,car parking space,room type,lead time,market segment type,repeated,P-C,P-not-C,average price,special requests,date of reservation,booking status
0,INN00001,1,1,2,5,Meal Plan 1,0,Room_Type 1,224,Offline,0,0,0,88.00,0,10-02-2015,Not_Canceled
1,INN00002,1,0,1,3,Not Selected,0,Room_Type 1,5,Online,0,0,0,106.68,1,11-06-2018,Not_Canceled
2,INN00003,2,1,1,3,Meal Plan 1,0,Room_Type 1,1,Online,0,0,0,50.00,0,2/28/2018,Canceled
3,INN00004,1,0,0,2,Meal Plan 1,0,Room_Type 1,211,Online,0,0,0,100.00,1,5/20/2017,Canceled
4,INN00005,1,0,1,2,Not Selected,0,Room_Type 1,48,Online,0,0,0,77.00,0,04-11-2018,Canceled

In [12]:

missingvalues = df.isnull().sum()
print(missingvalues)


df = df.dropna()
print("There are no null values in the dataset")

from sklearn.preprocessing import LabelEncoder
encode = LabelEncoder()
df['Booking_ID'] = encode.fit_transform(df['Booking_ID'])
df["room type"] = encode.fit_transform(df["room type"])
df["type of meal"] = encode.fit_transform(df["type of meal"])
df["booking status"] = encode.fit_transform(df["booking status"])
df["market segment type"] = encode.fit_transform(df["market segment type"])


q1 = df.select_dtypes(include='number').quantile(0.25)
q3 = df.select_dtypes(include='number').quantile(0.75)
iqr = q3 - q1

Booking_ID                   0
number of adults             0
number of children           0
number of weekend nights     0
number of week nights        0
type of meal                 0
car parking space            0
room type                    0
lead time                    0
market segment type          0
repeated                     0
P-C                          0
P-not-C                      0
average price               48
special requests             0
date of reservation          0
booking status               0
dtype: int64
There are no null values in the dataset

<ipython-input-12-02a789d2d4f0>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Booking_ID'] = encode.fit_transform(df['Booking_ID'])
<ipython-input-12-02a789d2d4f0>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["room type"] = encode.fit_transform(df["room type"])
<ipython-input-12-02a789d2d4f0>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["type of meal"] = encode.fit_transform(df["type of meal"])
<ipython-input-12-02a789d2d4f0>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["booking status"] = encode.fit_transform(df["booking status"])
<ipython-input-12-02a789d2d4f0>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["market segment type"] = encode.fit_transform(df["market segment type"])

In [15]:
outlier = ((df.select_dtypes(include='number') < (q1 - iqr * 1.5)) | (df.select_dtypes(include='number') > (q3 + iqr * 1.5))).any(axis=1)
df = df[~outlier]

In [16]:
#2
from sklearn.preprocessing import LabelEncoder
encode  = LabelEncoder()
df["room type"] = encode.fit_transform(df["room type"])
df["type of meal"] = encode.fit_transform(df["type of meal"])
df["booking status"] = encode.fit_transform(df["booking status"])
df["market segment type"] = encode.fit_transform(df["market segment type"])

In [18]:
#3
#removing duplicates
df.drop_duplicates()

,Booking_ID,number of adults,number of children,number of weekend nights,number of week nights,type of meal,car parking space,room type,lead time,market segment type,repeated,P-C,P-not-C,average price,special requests,date of reservation,booking status
14,14,2,0,0,2,0,0,0,47,2,0,0,0,94.50,2,10/20/2017,1
18,18,2,0,2,2,0,0,0,99,2,0,0,0,65.00,0,10/30/2017,0
19,19,2,0,1,0,0,0,0,12,1,0,0,0,72.00,0,10-04-2017,1
20,20,2,0,2,2,0,0,0,99,2,0,0,0,65.00,0,10/30/2017,0
22,22,2,0,2,4,0,0,0,2,1,0,0,0,85.00,0,3/20/2018,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36272,36224,2,0,2,6,0,0,0,148,2,0,0,0,98.39,2,07-01-2018,1
36274,36226,2,0,1,2,0,0,0,207,1,0,0,0,161.67,0,12/30/2018,1
36275,36227,2,0,1,2,0,0,0,224,1,0,0,0,65.00,0,10-02-2017,1
36278,36230,2,0,0,2,0,0,0,211,2,0,0,0,100.00,0,5/20/2018,0
36281,36233,2,0,1,3,0,0,0,34,2,0,0,0,107.55,1,10/15/2017,1

In [19]:

#4
from sklearn.model_selection import train_test_split
x=df.drop(["booking status","Booking_ID","date of reservation"],axis=1)
y=df["booking status"]

x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size=0.3,random_state=42)

In [20]:
#5
clf = LogisticRegression()
clf = clf.fit(x_train,y_train)
model = clf.predict(x_test)
print('predicted',model)
print()
print('test',y_test)

predicted [1 0 0 ... 0 1 1]

test 25810    1
30339    0
33450    1
6765     1
34107    1
        ..
2246     1
18592    1
34842    0
13604    1
13751    1
Name: booking status, Length: 3400, dtype: int64

In [24]:
#6
# accuracy = accuracy_score(y_test,model)
# precision = precision_score(y_test,model, average = 'weighted')
# recall = recall_score(y_test,model, average = 'weighted')
# f1 = f1_score(y_test,model, average = 'weighted')


from sklearn.metrics import classification_report

conf_matrix = confusion_matrix(y_test,model)
# print('accuracy: ',accuracy)
# print('precision: ',precision)
# print('recall: ',recall)
# print('f1: ',f1)

print(classification_report(y_test,model))
print('conf_matrix: ',conf_matrix)

              precision    recall  f1-score   support

           0       0.76      0.57      0.66      1059
           1       0.83      0.92      0.87      2341

    accuracy                           0.81      3400
   macro avg       0.80      0.75      0.76      3400
weighted avg       0.81      0.81      0.80      3400

conf_matrix:  [[ 608  451]
 [ 188 2153]]